/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silalita;

import Config.Config;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import static java.lang.Thread.sleep;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.JFrame;

/**
 *
 * @author admin
 */
public class InputData extends javax.swing.JFrame {
    static int detik = 0,menit = 0,jam = 0, mili=0;
    static int detikBck = 0,menitBck = 0,jamBck = 0, miliBck=0;
    static String valueGo, valueBack;
    static boolean startGo = false, startBack = false;
    
    List<Integer> idTamping = new ArrayList<Integer>();
    List<Integer> idPetugas = new ArrayList<Integer>();
    
    
    /**
     * Creates new form InputData
     */
    public InputData() {
        initComponents();
        setResizable(false);
        tampilCmbTamping();
        btnHistory.setBackground(new Color(0,0,0,0));
        btnHome.setBackground(new Color(0,0,0,0));
        btnSave.setBackground(new Color(0,0,0,0));
        btnStartGo.setBackground(new Color(0,0,0,0));
        btnStopGo.setBackground(new Color(0,0,0,0));
        btnStartBack.setBackground(new Color(0,0,0,0));
        btnStopBack.setBackground(new Color(0,0,0,0));
        
        cmbTamping.setBounds(100,100,100,30);
        
    }
    
    public void tampilCmbTamping() {
        try {
            String sql = "SELECT * FROM tamping WHERE status='Show'";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            
            idTamping.add(0);
            while(rs.next()){
                cmbTamping.addItem(rs.getString("nama_tamping"));
                idTamping.add(rs.getInt("id"));
                
            }
            pst.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void tampilCmbPetugas(int index) {
        try {
            String sql = "SELECT * FROM petugas WHERE id_tamping="+index;
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            idPetugas.clear();
            cmbNama.removeAllItems();
            cmbNama.addItem("--Pilih Nama--");
            idPetugas.add(0);
            while(rs.next()){
                cmbNama.addItem(rs.getString("petugas"));
                idPetugas.add(rs.getInt("id"));
                index++;
            }
            rs.close();
            pst.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JPanel();
        btnHistory = new javax.swing.JPanel();
        btnSave = new javax.swing.JPanel();
        btnStartGo = new javax.swing.JPanel();
        btnStopGo = new javax.swing.JPanel();
        btnStartBack = new javax.swing.JPanel();
        btnStopBack = new javax.swing.JPanel();
        txtTimerGo = new javax.swing.JLabel();
        txtTimerBack = new javax.swing.JLabel();
        cmbTamping = new javax.swing.JComboBox<>();
        txtJumlahTamping = new javax.swing.JTextField();
        txtKeperluan = new javax.swing.JTextField();
        cmbNama = new javax.swing.JComboBox<>();
        btnDataTamping = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 50));

        btnHistory.setPreferredSize(new java.awt.Dimension(200, 100));
        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnHistoryLayout = new javax.swing.GroupLayout(btnHistory);
        btnHistory.setLayout(btnHistoryLayout);
        btnHistoryLayout.setHorizontalGroup(
            btnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        btnHistoryLayout.setVerticalGroup(
            btnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 220, 50));

        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSaveLayout = new javax.swing.GroupLayout(btnSave);
        btnSave.setLayout(btnSaveLayout);
        btnSaveLayout.setHorizontalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        btnSaveLayout.setVerticalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 270, 50));

        btnStartGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartGoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnStartGoLayout = new javax.swing.GroupLayout(btnStartGo);
        btnStartGo.setLayout(btnStartGoLayout);
        btnStartGoLayout.setHorizontalGroup(
            btnStartGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        btnStartGoLayout.setVerticalGroup(
            btnStartGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(btnStartGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 140, 30));

        btnStopGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopGoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnStopGoLayout = new javax.swing.GroupLayout(btnStopGo);
        btnStopGo.setLayout(btnStopGoLayout);
        btnStopGoLayout.setHorizontalGroup(
            btnStopGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        btnStopGoLayout.setVerticalGroup(
            btnStopGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(btnStopGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 30));

        btnStartBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnStartBackLayout = new javax.swing.GroupLayout(btnStartBack);
        btnStartBack.setLayout(btnStartBackLayout);
        btnStartBackLayout.setHorizontalGroup(
            btnStartBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        btnStartBackLayout.setVerticalGroup(
            btnStartBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(btnStartBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 150, 40));

        btnStopBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnStopBackLayout = new javax.swing.GroupLayout(btnStopBack);
        btnStopBack.setLayout(btnStopBackLayout);
        btnStopBackLayout.setHorizontalGroup(
            btnStopBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        btnStopBackLayout.setVerticalGroup(
            btnStopBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(btnStopBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 150, 30));

        txtTimerGo.setFont(new java.awt.Font("Arial Hebrew", 1, 48)); // NOI18N
        txtTimerGo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTimerGo.setText("00:00:00");
        getContentPane().add(txtTimerGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 200, 40));

        txtTimerBack.setFont(new java.awt.Font("Arial Hebrew", 1, 48)); // NOI18N
        txtTimerBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTimerBack.setText("00:00:00");
        getContentPane().add(txtTimerBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 310, 80));

        cmbTamping.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        cmbTamping.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Tamping--" }));
        cmbTamping.setToolTipText("Pilih Tamping");
        cmbTamping.setMinimumSize(new java.awt.Dimension(255, 30));
        cmbTamping.setPreferredSize(new java.awt.Dimension(214, 50));
        cmbTamping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTampingActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTamping, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 170, 30));

        txtJumlahTamping.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtJumlahTamping.setBorder(null);
        txtJumlahTamping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahTampingActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlahTamping, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 150, 30));

        txtKeperluan.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtKeperluan.setBorder(null);
        txtKeperluan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeperluanActionPerformed(evt);
            }
        });
        getContentPane().add(txtKeperluan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 150, 30));

        cmbNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Nama--" }));
        cmbNama.setToolTipText("Pilih Nama");
        getContentPane().add(cmbNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 170, 180, 30));

        btnDataTamping.setBackground(new java.awt.Color(255, 255, 255));
        btnDataTamping.setText("Data Tamping");
        btnDataTamping.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDataTamping.setBorderPainted(false);
        btnDataTamping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDataTampingMouseClicked(evt);
            }
        });
        btnDataTamping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataTampingActionPerformed(evt);
            }
        });
        getContentPane().add(btnDataTamping, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/InputTamping.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        dispose();
        Dashboard db = new Dashboard();
        db.setVisible(true);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseClicked
        dispose();
        HistoryTamping ht = new HistoryTamping();
        ht.setVisible(true);
    }//GEN-LAST:event_btnHistoryMouseClicked

    private void btnStartGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartGoMouseClicked
        startGo = true;
        PreviewTimer pt = new PreviewTimer();
//        pt.setVisible(true);
        pt.t.setText("500000");
        
        Thread t = new Thread() {
            public void run(){
                for(;;) {
                    if (startGo == true) {
                        try {
                            sleep(1);

                            if (mili >1000) {
                                mili = 0;
                                detik++;
                            } else if (detik > 60) {
                                detik = 0;
                                menit++;
                            } else if (menit > 60) {
                                menit = 0;
                                jam++;
                            }
                            
                            mili++;
                            String tmpMenit = (menit==0) ? "00" : Integer.toString(menit);
                            String tmpJam = (jam==0) ? "00" : Integer.toString(jam);
                            txtTimerGo.setText(tmpJam +":"+tmpMenit +":"+detik);
                            valueGo = txtTimerGo.getText();
                        } catch (Exception e) {
                        }
                    } else {
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_btnStartGoMouseClicked

    private void btnStopGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopGoMouseClicked
        startGo = false;
    }//GEN-LAST:event_btnStopGoMouseClicked

    private void btnStartBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartBackMouseClicked
        startBack = true;
        
        
        Thread t = new Thread() {
            public void run(){
                for(;;) {
                    if (startBack == true) {
                        try {
                            sleep(1);

                            if (miliBck >1000) {
                                miliBck = 0;
                                detikBck++;
                            } else if (detikBck > 60) {
                                detikBck = 0;
                                menitBck++;
                            } else if (menitBck > 60) {
                                menitBck = 0;
                                jamBck++;
                            }
                            
                            miliBck++;
                            String tmpMenit = (menitBck==0) ? "00" : Integer.toString(menitBck);
                            String tmpJam = (jamBck==0) ? "00" : Integer.toString(jamBck);
                            txtTimerBack.setText(tmpJam +":"+tmpMenit +":"+detikBck);
                            valueBack = txtTimerBack.getText();
                        } catch (Exception e) {
                        }
                    } else {
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_btnStartBackMouseClicked

    private void btnStopBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopBackMouseClicked
        startBack = false;
    }//GEN-LAST:event_btnStopBackMouseClicked

    private void txtJumlahTampingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahTampingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahTampingActionPerformed

    private void cmbTampingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTampingActionPerformed
//        System.out.println(idTamping[cmbTamping.getSelectedIndex()]);
tampilCmbPetugas(idTamping.get(cmbTamping.getSelectedIndex()));
    }//GEN-LAST:event_cmbTampingActionPerformed

    private void txtKeperluanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeperluanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeperluanActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        inputTamping();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnDataTampingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataTampingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataTampingActionPerformed

    private void btnDataTampingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataTampingMouseClicked
         InputTamping it = new InputTamping();
        it.setVisible(true);
    }//GEN-LAST:event_btnDataTampingMouseClicked
    
    private void inputTamping(){
        try {
            if (txtJumlahTamping.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Jumlah Tamping Tidak Boleh Kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if(txtKeperluan.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Keperluan Tidak Boleh Kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if(startGo==true || startBack==true){
                JOptionPane.showMessageDialog(null, "Waktu masih berjalan", "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else {
                 String sql = "INSERT INTO history(id_tamping, id_petugas,keperluan, jumlah, waktu_berangkat, waktu_kembali, created_at) VALUES(?,?,?,?,?,?,?)";
                 
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                LocalDateTime now = LocalDateTime.now();
                 try {
                    pst.setString(1, idTamping.get(cmbTamping.getSelectedIndex()).toString());
                    pst.setString(2, idPetugas.get(cmbNama.getSelectedIndex()).toString());
                    pst.setString(3, txtJumlahTamping.getText());
                    pst.setString(4, txtKeperluan.getText());
                    pst.setString(5, valueGo);
                    pst.setString(6, valueBack);
                    pst.setString(7, dtf.format(now).toString());
                    pst.executeUpdate();
                    resetForm();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Dimpan "+e);
                System.out.println(e);
            }
            pst.close();
                
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void resetForm(){
        txtJumlahTamping.setText("");
        txtKeperluan.setText("");
        txtTimerGo.setText("00:00:00");
        txtTimerBack.setText("00:00:00");
        detik = 0;
        menit = 0;
        jam = 0; 
        mili=0;
        detikBck = 0;
        menitBck = 0;
        jamBck = 0;
        miliBck=0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataTamping;
    private javax.swing.JPanel btnHistory;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnSave;
    private javax.swing.JPanel btnStartBack;
    private javax.swing.JPanel btnStartGo;
    private javax.swing.JPanel btnStopBack;
    private javax.swing.JPanel btnStopGo;
    private javax.swing.JComboBox<String> cmbNama;
    private javax.swing.JComboBox<String> cmbTamping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtJumlahTamping;
    private javax.swing.JTextField txtKeperluan;
    private javax.swing.JLabel txtTimerBack;
    private javax.swing.JLabel txtTimerGo;
    // End of variables declaration//GEN-END:variables
}
